title: Just a text title
author: jassoncordones
email: jasson.cordones@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a test blog made from a github learning lab course.

# social links
twitter_username: jassoncordones # DO NOT include the @ character, or else the build will fail!
github_username:  jassoncordones # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
